//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnityTest_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.Transactions = new HashSet<Transactions>();
            this.TransactionPeriodique = new HashSet<TransactionPeriodique>();
        }
    
        public int id { get; set; }
        public int idPorteFeuille { get; set; }
        public string designation { get; set; }
        public string descript { get; set; }
    
        public virtual PorteFeuille PorteFeuille { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
        public virtual ICollection<TransactionPeriodique> TransactionPeriodique { get; set; }
    }
}
